export const categories = {
    9: "category.general",
    10: "category.books",
    11: "category.film",
    12: "category.music",
    13: "category.musicals",
    14: "category.television",
    15: "category.videogames",
    16: "category.boardgames",
    17: "category.science",
    18: "category.computers",
    19: "category.math",
    20: "category.mythology",
    21: "category.sports",
    22: "category.geography",
    23: "category.history",
    24: "category.politics",
    25: "category.art",
    26: "category.celebrities",
    27: "category.animals",
    28: "category.vehicles",
    29: "category.comics",
    30: "category.gadgets",
    31: "category.anime",
    32: "category.cartoon",
};
